### ISSUE TITLE
Question about detect intersection on the 12 edges

### ISSUE THREAD

**Issue by ccyycc1994** [czq142857/BSP-NET-original#3]
Dear author:
           Thank you for sharing the whole code.
           In bspy_2d.py: line 24~40, (also in bspy_slow.py)
                fisrt use whether |a| is larger than |b| or nor to get the intersection of edge, but then it seems like to use
                the condition 'a>0' or 'b<0' to decide the order of point in the face.
                I'm confused about this condition. If it is convenient,  could you explain it.
           Thanks

**Comment by czq142857** [comment]
In 2D case, abs(a)>=abs(b) decides which edges to intersect with a unit box:
![image](https://user-images.githubusercontent.com/24209790/86871739-b8b5cd00-c08f-11ea-8866-a23fbd26eb12.png)

The condition 'a>0' or 'b<0' decides the order of points in the face, because the order of points decides the normal direction of the face, and the normal direction can be infered from a and b.
